# Site settings
title: Sonya Simkin
description: Sonya Simkin's personal website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://sonyasimk.github.io"
domain: "sonyasimk.github.io"

# User settings
username: Sonya Simkin
user_description: I am an M.S. student in the School of Computer Science at Carnegie Mellon University, advised by [Stephanie Balzer](https://www.cs.cmu.edu/~balzers/).
# user_title: Software Developer
email: ssimkin@andrew.cmu.edu
github_username: sonyasimk

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
