# Site settings
title: Sonya Simkin
description: Sonya Simkin's personal website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://sonyasimk.github.io"
domain: "sonyasimk.github.io"

# User settings
username: Sonya Simkin
email: ssimkin@andrew.cmu.edu
github_username: sonyasimk

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
